# Generated by Django 4.2.23 on 2025-07-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(max_length=128)),
                ('downstream_service', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('method', models.CharField(max_length=10)),
                ('response_status', models.IntegerField()),
                ('duration_ms', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Unique identifier used in the proxy URL', max_length=100, unique=True)),
                ('base_url', models.URLField(help_text="Base URL of the downstream service. Don't Include '/' in the end of url  E.g., https://httpbin.org")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
